# Selecciona una imagen base
FROM python:3.11

# Establece el directorio de trabajo en la imagen
WORKDIR /app

# Copia los archivos de tu aplicación Flask al directorio de trabajo
COPY . /app

# Instala las dependencias
RUN pip install -r requirements.txt

# Expone el puerto en el que se ejecutará tu aplicación Flask
EXPOSE 5000

# Define el comando para ejecutar tu aplicación Flask
CMD ["python", "controladorGeneral.py"]
